# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amp', '0003_auto_20170802_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.TextField()),
                ('artist', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='num_tracks',
            field=models.IntegerField(default=0),
        ),
    ]
